parameters:
#    user_data.example.class: User\DataBundle\Example

services:
#    user_data.example:
#        class: %user_data.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
